### ISSUE TITLE
Remove glid

### ISSUE THREAD

**Issue by a7i** [vsouza/go-gin-boilerplate#2]
Request to remove glide yaml to avoid confusion since it's now replaced by godeps

**Comment by vsouza** [comment]
@a7i thanks for your suggestion. Personally, I prefer glide than Godeps or Govendor. According to this table, we have more benefits using Glide.

https://github.com/Masterminds/glide/wiki/Go-Package-Manager-Comparison

I'll close this issue, for now, feel free to reopen anytime.
